---
- name: Ensure MySQL packages are installed.
  yum: "name={{ mysql_packages }} state=present enablerepo={{ mysql_enablerepo }}"
  register: rh_mysql_install_packages

- name: Ensure MySQL Python libraries are installed.
  yum: "name=MySQL-python state=present enablerepo={{ mysql_enablerepo }}"
