- name: Make sure nodejs related packages are removed.
  tags: npm
  apt: name="nodejs" state=absent purge=yes

- name: Added repository for new nodejs.
  remote_user: deployer
  tags: npm
  raw:  wget -qO- https://deb.nodesource.com/setup_8.x | sudo -E bash -

- name: Install nodejs.
  remote_user: deployer
  tags: npm
  apt: name=nodejs state=present

- name: Install libpng-dev.
  remote_user: deployer
  tags: npm
  apt: name=libpng-dev state=present
